apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs-staging
  namespace: argocd
spec:
  project: sample-nodejs-staging
  sources:
    - repoURL: https://github.com/OdedPerez/sample-nodejs.git
      targetRevision: main
      path: helm/sample-nodejs
      helm:
        valueFiles:
          - $values/staging/values.yaml
    - repoURL: https://github.com/OdedPerez/sample-nodejs-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-nodejs-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
