apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs-prod
  namespace: argocd
spec:
  project: sample-nodejs-prod
  source:
    repoURL: https://github.com/OdedPerez/sample-nodejs-gitops.git
    targetRevision: main
    path: helm/sample-nodejs
    helm:
      valueFiles:
        - ../../production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-nodejs-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
